FROM --platform=linux/amd64 python:3.8

ARG PYINSTALLER_VERSION

VOLUME /opt/src/
WORKDIR /opt/src/

RUN python -m pip install --upgrade pip  \
    && pip install pyinstaller==$PYINSTALLER_VERSION

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

